### ISSUE TITLE
Unable to install Jobs-multi on WAMP.

### ISSUE THREAD

**Issue by theShiva** [jobapis/jobs-multi#11]
Hi,

I am trying to install jobs-multi on a Windows WAMP setup. I downloaded and installed composer for Windows. Then I cloned this repo (i.e. jobs-multi ) and opened a cmd window, cd-ed to my folder (shown below ) and ran the composer require command.

Am getting the following error. What am I doing wrong? (I'm new to PHP so please bear with me.

![image](https://cloud.githubusercontent.com/assets/1057194/21747903/1bd6dc48-d52b-11e6-8727-0787dc723697.png)

**Comment by theShiva** [comment]
My bad. User error lol. 

For the benefit of others....  I was trying install jobs-multi within the repo itself. That was the issue. I created an empty folder (which is where I guess I would write PHP code to use the Jobs-Multi API?) and ran the commands and they worked successfully. 

![image](https://cloud.githubusercontent.com/assets/1057194/21747937/d9867604-d52b-11e6-962d-27e3b2c971a3.png)


Also see the libraries in the folders as expected.

![image](https://cloud.githubusercontent.com/assets/1057194/21747942/ee4fd530-d52b-11e6-9d83-f108407d34a6.png)

**Comment by karllhughes** [comment]
Thanks for closing. Let me know if you run into any other issues as I haven't done much work on Windows in a while.
