### ISSUE TITLE
Pagination setup for Jobs-multi wrapper

### ISSUE THREAD

**Issue by TechnoPHP** [jobapis/jobs-multi#12]
$client = new JobApis\Jobs\Client\JobsMulti($providers);
$jobs = $client->setKeyword('engineering')
    ->setLocation('chicago, il')
    ->setPage(1, 10)
	->getAllJobs($options);
This is the code we use. If we set the $options['maxResults'=>100], the setPage( ) method does not work.
In the case above it should return 10 results from the $jobs object I believe.
Secondly, how to set up the pagination at the end of the list that example is missing.
Great work and useful code package to make a job board.

**Comment by karllhughes** [comment]
@TechnoPHP thanks for your question. What happens when you use the `setPage` method like this? Does it throw an error saying that the method is not found or does it just return too many results?

I think the docs may be wrong and that the setPage method isn't fully implemented.

**Comment by TechnoPHP** [comment]
When I use the same code and in the $options array I use $options['maxResults'=>100], then also I must get 10 items per page right?
I get almost 38 items.
Also there is lack of example which shows setting up the pagination.

**Comment by karllhughes** [comment]
@TechnoPHP ok, I'll look into this and report back. Thanks for bringing up the issue!

**Comment by karllhughes** [comment]
@TechnoPHP so I think the documentation is a bit confusing. Here's the way it currently works:

- the `setPage` method sets the page and number of results per page **for each provider** being queried.
- the `maxResults` option sets the total number of results to return for all providers.

I think you expected that `setPage` would work on the whole collection, which would probably be a good idea. That is a breaking change though, so I'll have to consider it for future release.

**Comment by TechnoPHP** [comment]
Thanks Karl, 
Yes I expected that setPage should work for the whole collection of jobs. It make sense to developers.
Also it would be appreciated if some of the example code posted how to display the pagination numbers once it is released.
My good luck to communicate with you.

**Comment by karllhughes** [comment]
Sounds like me take away from this is better documentation for pagination queries. I'll make a note to do this sometime in the next week.

**Comment by karllhughes** [comment]
@TechnoPHP I've updated the docs to clarify the intent of the `setPage` method.

Since each provider does not allow consistent pagination, it's impossible to navigate pages of *all* results from all providers unless this library implemented some kind of storage system.

Anyway, I may try to address this in a future major version release, but there's not currently one on my roadmap, so I'm closing the issue for now. Let me know if you have any further questions!

**Comment by TechnoPHP** [comment]
Thank you Karl, We will wait for the new release. I'll try to contribute the code in this case if possible for me to grab time from client.
