### ISSUE TITLE
Unable to duplicate README.md basic use example

### ISSUE THREAD

**Issue by gpolyn** [jobapis/jobs-multi#14]
Encounter an error when I attempt to execute the script given in the README.md:

`Fatal error: Class 'JobsMulti' not found in /(snip!)/hello-jobapis/hellojobsmulti.php on line 20`

Have duped my effort in a repo at [github.com/gpolyn/hello-jobapis](https://github.com/gpolyn/hello-jobapis)

Please consider and suggest remedy.

G

**Comment by karllhughes** [comment]
@gpolyn I think you'll need to use the fully qualified class name and path or a `use`statement at the top of the php file.

I am going to revisit the documentation this week as there are now a couple open questions about it. If you have any suggestions or want to submit a PR based on your experience I welcome it!

**Comment by gpolyn** [comment]
@karllhughes thanks!

Inspired by your comment, I made some changes and I now have success (https://github.com/gpolyn/hello-jobapis/commit/ced171244039f06d310372934204e9cb82823520).

Not sure what you want to do, here, but I consider the issue closed, now.

**Comment by karllhughes** [comment]
Good to hear. Thanks!
