### ISSUE TITLE
Unable to install Jobs Multi API on localhost (Windows/XAMPP)

### ISSUE THREAD

**Issue by ibbu786** [jobapis/jobs-multi#16]
I am are trying to set up Jobs Multi at my localhost (Windows/XAMPP). For that I have installed Composer and created a empty directory in my xampp\htdocs\directory-for-jobs-multi and ran given commands but its not working. It is just creating a composer.json file with {} only opening and closing curly braces and command in CMD get stuck in processing only. I tried to search solution for this issue but did not found anything on web.

I will be really grateful if anyone can help to fix this issue.

**Comment by karllhughes** [comment]
When you navigate to the directory you created for the project and run `composer require jobapis/jobs-multi` what output do you see in your command line console? Is there an error?

**Comment by ibbu786** [comment]
As I said it is just creating a composer.json file with {} only opening and closing curly braces and command in CMD get stuck in processing only and shows no error.

**Comment by karllhughes** [comment]
Sounds like either a Composer error or a network connection issue. What happens when you require another Composer package? Something like `composer require phpunit/phpunit`.

**Comment by ibbu786** [comment]
Have not tried any other Composer package. I will try other package once I am on my system and get back. If that also does not work then will reinstall Composer and try again. But what if that also does not work? What can be done next to make this work?

**Comment by karllhughes** [comment]
If that doesn't work, then maybe find someone who knows XAMPP. I'm only familiar with Mac/Linux, so if there's something wrong in XAMPP's setup, I probably can't help.

Have you done much PHP development before or is this your first time?

**Comment by ibbu786** [comment]
Have created quite a few applications in PHP and XAMPP is installed just fine. Have not faced any issues with XAMPP whatsoever. Though this is my first time with Composer.

**Comment by karllhughes** [comment]
Ok, well maybe there is some trick to using Composer with XAMPP. I'm assuming you ran through the Windows setup instructions? https://getcomposer.org/doc/00-intro.md#installation-windows

**Comment by ibbu786** [comment]
Yes, have checked the instructions. Let me get back to my system on Monday and will get back to you.

**Comment by ibbu786** [comment]
Re-installing composer did the trick. Thanks for your help.
