### ISSUE TITLE
No jobs returned for Dice

### ISSUE THREAD

**Issue by ibbu786** [jobapis/jobs-multi#17]
Have tried with every possible combination but every time it just says "0 Jobs Found". Can anyone please help me in getting jobs returned from Dice API.

Thanks in advance.

**Comment by karllhughes** [comment]
Last week I noticed this too. I believe Dice has shut down the API we were using.

I'll look into upgrading the Dice client.

**Comment by ibbu786** [comment]
Okay. Thank you for your response. Will wait for the update.

**Comment by karllhughes** [comment]
I don't see a new version of their API documented, so I emailed their PR person. Will start emailing tech people if I don't hear anything next week.

**Comment by karllhughes** [comment]
I also reached out to Dice via this form: http://techhub.dice.com/Dice_General-ContactUs_D.html

No response yet. Will check in again in a week or two.

**Comment by ibbu786** [comment]
Do you want me to contact them as well?

**Comment by karllhughes** [comment]
I guess it can't hurt. A couple people have asked about this, so if you do hear back, let us know here.

Thanks!

**Comment by karllhughes** [comment]
@ibbu786 another user called me today after he got in touch with Dice. Apparently they've decided to shut down the public API in favor of only working with paying customers.

It's unfortunate, but this is their choice.

I'm going to make a note to shut down [the `jobs-dice` library](https://github.com/jobapis/jobs-dice) I support as well as remove it from `jobs-multi`. Might take me a couple weeks to get to it as I have some travel lined up.

Thanks again for bringing this to my attention, and best of luck!

**Comment by ibbu786** [comment]
Thanks for the update.
