### ISSUE TITLE
Documentation - How do I use this API? What are the Endpoints?

### ISSUE THREAD

**Issue by theShiva** [jobapis/jobs-multi#9]
Hi,

It looks like the jobsApis.com provides an API to query various Job sites in 1 place. How do I get started? I would like to filter job listing from the job sites you listed, for a niche domain, and publish them on a custom job board.

thank you!

-Shiva

**Comment by karllhughes** [comment]
Hey Shiva, sounds like our info on JobApis wasn't clear enough. We provide this package of code as a simple way for developers to access several job board APIs with as little effort as possible. We do not currently host an API to access this data directly.

If you'd like to use this package for a PHP project, you can follow the instructions in the readme. If you'd like help or are interested in an API for all job boards, you can email me and we can talk more about that as well: khughes.me@gmail.com

Good luck!
